function contacts() {
  return [
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
    {
      name: 'Usama',
      messages: [
        'This is the testing message 01',
        'This is the testing message 02',
        'This is the testing message 03',
        'This is the testing message 04',
        'This is the testing message 05',
        'This is the testing message 06',
        'This is the testing message 07',
        'This is the testing message 08',
        'This is the testing message 09',
      ],
    },
  ];
}

export default contacts;
